jobs:
  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        arch: [x64, arm64]
        exclude:
          - platform: macos-latest
            arch: arm64 # 不处理 macOS 下的 ARM 构建

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      ...

      - name: Install Rust target for ARM64
        if: matrix.arch == 'arm64' && matrix.platform == 'ubuntu-latest'
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install cross for cross-compiling
        if: matrix.arch == 'arm64' && matrix.platform == 'ubuntu-latest'
        run: cargo install cross

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf \
            libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            qemu-user qemu-user-static

      # 构建 Tauri app
      - name: Build Tauri app (x64)
        if: matrix.arch == 'x64'
        run: pnpm run tauri build

      - name: Build Tauri app (arm64 with cross)
        if: matrix.arch == 'arm64' && matrix.platform == 'ubuntu-latest'
        run: |
          cross build --target aarch64-unknown-linux-gnu --release
          pnpm run tauri build --target aarch64-unknown-linux-gnu

      - name: Rename artifacts (Ubuntu ARM64)
        if: matrix.arch == 'arm64' && matrix.platform == 'ubuntu-latest'
        run: |
          cd src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage
          mv "AI 学院_0.1.0_aarch64.AppImage" "app_0.1.0_arm64.AppImage"
          tar -czf app_0.1.0_arm64.AppImage.tar.gz app_0.1.0_arm64.AppImage

      ...

      - uses: tauri-apps/tauri-action@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
          includeDebugArtifacts: true
          releaseDraft: false
          prerelease: false
          publish: true
