name: Release CI

on:
  push:
    tags:
      - 'v*' # e.g., v1.0.0

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

    steps:
      - uses: actions/checkout@v2
      - name: Query version number
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.get_version.outputs.version }}'
          release_name: 'App ${{ steps.get_version.outputs.version }}'
          body: 'See the assets to download this version.'
          draft: false
          prerelease: false

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            arch: amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - platform: macos-arm64
            arch: arm64
            runner: macos-14
            target: aarch64-apple-darwin
          - platform: ubuntu-latest
            arch: amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - platform: ubuntu-arm64
            arch: arm64
            runner: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2

      - name: Query version number
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v1

      - name: Install cross (for Linux arm64)
        if: matrix.arch == 'arm64' && matrix.runner == 'ubuntu-latest'
        run: cargo install cross

      - name: Install Linux dependencies
        if: matrix.runner == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV

      - name: Install and build
        run: pnpm install

      - name: Build Tauri app
        run: |
          if [ "${{ matrix.runner }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            cross build --release --target=${{ matrix.target }}
          else
            pnpm tauri build --target ${{ matrix.target }}
          fi

      - name: Rename and archive artifacts
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          cd src-tauri/target/${{ matrix.target }}/release/bundle || cd src-tauri/target/release/bundle
          mkdir -p artifacts
          if [[ "${{ matrix.target }}" == *"apple-darwin" ]]; then
            find dmg -name "*.dmg" -exec cp {} artifacts/app_${VERSION}_${{ matrix.arch }}.dmg \;
            find macos -name "*.app" -exec tar -czf artifacts/app_${VERSION}_${{ matrix.arch }}.app.tar.gz {} \;
          elif [[ "${{ matrix.target }}" == *"linux-gnu" ]]; then
            find deb -name "*.deb" -exec cp {} artifacts/app_${VERSION}_${{ matrix.arch }}.deb \;
            find appimage -name "*.AppImage" -exec tar -czf artifacts/app_${VERSION}_${{ matrix.arch }}.AppImage.tar.gz {} \;
          fi

      - name: Upload to GitHub Release
        uses: tauri-apps/tauri-action@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
          includeDebugArtifacts: true
          releaseDraft: false
          prerelease: false
          publish: true
