name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: 'Publish Tauri App'
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: macos
            target: aarch64-apple-darwin
            use_emulator: false

          - os: macos-latest
            platform: macos
            target: x86_64-apple-darwin
            use_emulator: false

          - os: ubuntu-22.04
            platform: linux
            target: ''
            use_emulator: false

          - os: windows-latest
            platform: windows
            target: ''
            use_emulator: false

          - os: ubuntu-latest
            platform: linux-arm64
            target: aarch64-unknown-linux-gnu
            use_emulator: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Install Rust
        if: ${{ !matrix.use_emulator }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        if: ${{ !matrix.use_emulator }}
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Linux dependencies
        if: ${{ runner.os == 'Linux' && !matrix.use_emulator }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Build with ARM Emulator
        if: matrix.use_emulator
        uses: pguyot/arm-runner-action@v2.6.5
        with:
          base_image: debian:bullseye
          cpu: cortex-a72
          cpu_arch: arm64
          bind_mount_repository: true
          commands: |
            apt-get update
            apt-get install -y curl libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            export PATH="$HOME/.cargo/bin:$PATH"
            rustup target add ${{ matrix.target }}
            pnpm install
            cd src-tauri
            pnpm tauri build --target ${{ matrix.target }}

      - name: Build Tauri App
        if: ${{ !matrix.use_emulator }}
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ matrix.target && format('--target {0}', matrix.target) || '' }}
          releaseDraft: false
          uploadArtifacts: false

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: true
          overwrite: true
          files: |
            src-tauri/target/**/release/bundle/**/*.dmg
            src-tauri/target/**/release/bundle/**/*.msi
            src-tauri/target/**/release/bundle/**/*.exe
            src-tauri/target/**/release/bundle/**/*.AppImage
            src-tauri/target/**/release/bundle/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
