# 可选，将显示在 GitHub 存储库的"操作"选项卡中的工作流名称
name: Release CI
 
# 指定此工作流的触发器
on:
  push:
    # 匹配特定标签 (refs/tags)
    tags:
      - 'v*' # 推送事件匹配 v*, 例如 v1.0，v20.15.10 等来触发工作流
 
# 需要运行的作业组合
jobs:
  # 任务：创建 release 版本
  create-release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}
 
    steps:
      - uses: actions/checkout@v2
      # 查询版本号（tag）
      - name: Query version number
        id: get_version
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"
 
      # 根据查询到的版本号创建 release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{ steps.get_version.outputs.VERSION }}'
          release_name: 'app ${{ steps.get_version.outputs.VERSION }}'
          body: 'See the assets to download this version and install.'
          draft: false
          prerelease: false

  # 编译 Tauri
  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        include:
          - platform: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      # 安装 Node.js
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      # 使用 pnpm 缓存
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 安装 Rust
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      # 使用 Rust 缓存，加快安装速度
      - uses: Swatinem/rust-cache@v1

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y pkg-config
          # 安装 ARM64 的系统库
          sudo apt-get install -y libgtk-3-dev:arm64 libwebkit2gtk-4.0-dev:arm64 \
            libappindicator3-dev:arm64 librsvg2-dev:arm64 patchelf:arm64 \
            libjavascriptcoregtk-4.1-dev:arm64 libwebkit2gtk-4.1-dev:arm64
          # 安装 qemu 支持
          sudo apt-get install -y qemu-user-static
          # 设置交叉编译环境变量
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu" >> $GITHUB_ENV
          # 设置 dpkg 架构
          sudo dpkg --add-architecture arm64

      - name: install dependencies (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          # 安装 WiX 工具集
          $WIX_VERSION = "3.14.0"
          $WIX_URL = "https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314-binaries.zip"
          $WIX_PATH = "C:\wix"
          
          # 确保目录存在
          if (-not (Test-Path $WIX_PATH)) {
              New-Item -ItemType Directory -Force -Path $WIX_PATH
          }
          
          # 下载并解压 WiX
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri $WIX_URL -OutFile "$WIX_PATH\wix.zip"
          Expand-Archive -Path "$WIX_PATH\wix.zip" -DestinationPath $WIX_PATH -Force
          
          # 设置环境变量
          $env:PATH = "$WIX_PATH;$env:PATH"
          $env:WIX = $WIX_PATH
          
          # 验证安装
          Write-Host "Verifying WiX installation..."
          if (Test-Path "$WIX_PATH\candle.exe") {
              Write-Host "candle.exe found at $WIX_PATH\candle.exe"
              & "$WIX_PATH\candle.exe" -version
          } else {
              Write-Error "candle.exe not found"
          }
          
          if (Test-Path "$WIX_PATH\light.exe") {
              Write-Host "light.exe found at $WIX_PATH\light.exe"
              & "$WIX_PATH\light.exe" -version
          } else {
              Write-Error "light.exe not found"
          }
          
          # 设置 Tauri 的 WiX 路径
          $env:TAURI_WIX_DIR = $WIX_PATH

      # 可选，如果需要将 Rust 编译为 wasm，则安装 wasm-pack
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: v0.9.1
 
      # 可选，如果需要使用 rsw 构建 wasm，则安装 rsw
      - name: Install rsw
        run: cargo install rsw
 
      # 安装依赖执行构建，以及推送 github release
      - name: Install app dependencies and build it
        run: |
          pnpm install
          if [ "${{ matrix.platform }}" == "ubuntu-latest" ]; then
            pnpm run build
            cd src-tauri
            # 确保使用正确的 pkg-config
            PKG_CONFIG_ALLOW_CROSS=1 \
            PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
            PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu \
            cargo build --target aarch64-unknown-linux-gnu --release
            cd ..
            npx tauri build --target aarch64-unknown-linux-gnu
          else
            pnpm pubhome
          fi

      - name: Rename artifacts
        run: |
          cd src-tauri/target/release/bundle
          if [ "${{ matrix.platform }}" == "macos-latest" ]; then
            # macOS 重命名
            mv "macos/AI 学院.app" "macos/app.app"
            mv "dmg/AI 学院_0.1.0_aarch64.dmg" "dmg/app_0.1.0_arm64.dmg"
            cd macos
            tar -czf app.app.tar.gz app.app
          elif [ "${{ matrix.platform }}" == "ubuntu-latest" ]; then
            cd ../aarch64-unknown-linux-gnu/release/bundle
            # Linux ARM 重命名
            mv "deb/AI 学院_0.1.0_arm64.deb" "deb/app_0.1.0_arm64.deb"
            mv "appimage/AI 学院_0.1.0_arm64.AppImage" "appimage/app_0.1.0_arm64.AppImage"
            cd appimage
            tar -czf app_0.1.0_arm64.AppImage.tar.gz app_0.1.0_arm64.AppImage
          elif [ "${{ matrix.platform }}" == "windows-latest" ]; then
            # Windows 重命名
            mv "msi/AI 学院_0.1.0_x64_en-US.msi" "msi/app_0.1.0_x64_en-US.msi"
            mv "nsis/AI 学院_0.1.0_x64-setup.exe" "nsis/app_0.1.0_x64-setup.exe"
          fi

      - uses: tauri-apps/tauri-action@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}
          includeDebugArtifacts: true
          releaseDraft: false
          prerelease: false
          publish: true